name: RatCusReputation
main: org.plugin.RatCusReputation
author: _LuK__
version: 1.0
database: true

commands:
  repadmin:
    description: Команда для модерации
    aliases: [repa]
    permission: reputation.moderator
    permission-message: §c| У вас нет прав для использования этой команды
  reputation:
    description: Главная команда репутации
    aliases: [rep]
  like:
    description: Команда лайка
  dislike:
    description: Команда дизлайка

permissions:
  reputation.moderator:
    description: Право на использование модераторских команд
